name: Release

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["linux"]
        arch: ["arm64", "amd64"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o yaml-env-replacer-${{ matrix.os }}-${{ matrix.arch }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        prerelease: true
        files: |
          yaml-env-replacer-${{ matrix.os }}-${{ matrix.arch }}
      
